apiVersion: 1

notifiers:
  - name: EmailNotifier
    type: email
    uid: email_notifier
    org_id: 1
    is_default: true
    settings:
      addresses: admin@seu-dominio.com
    secureSettings:
      password: ""

deleteNotifiers: [] 