version: '3.8'

services:
  comfyui:
    build:
      context: ../comfy
      dockerfile: Dockerfile
    container_name: comfyui
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COMFYUI_API_KEY=${COMFYUI_API_KEY:-}
    volumes:
      - ../models:/workspace/models
      - ../outputs:/workspace/outputs
      - ../logs:/workspace/logs
    ports:
      - "8188:8188"  # Interface web
      - "8000:8000"  # Métricas Prometheus
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - comfy-net

  nginx:
    image: nginx:alpine
    container_name: comfy-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - comfyui
    networks:
      - comfy-net

networks:
  comfy-net:
    driver: bridge 