apiVersion: 1

groups:
  - name: DiskAlerts
    folder: System
    interval: 1m
    rules:
      - title: Alto Uso de Disco
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"})
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 80
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: threshold
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Uso de disco acima de 80%
        labels:
          severity: warning
          
      - title: Uso de Disco Crítico
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"})
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 90
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: threshold
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Uso de disco acima de 90% - Situação Crítica
        labels:
          severity: critical 