apiVersion: 1

groups:
  - name: HealthcheckAlerts
    folder: System
    interval: 30s
    rules:
      - title: API Healthcheck Falhou
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: up{job="api"} == 0
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: threshold
        noDataState: Alerting
        execErrState: Error
        for: 1m
        annotations:
          summary: API está inacessível
        labels:
          severity: critical
          
      - title: Redis Healthcheck Falhou
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: up{job="redis"} == 0
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: threshold
        noDataState: Alerting
        execErrState: Error
        for: 1m
        annotations:
          summary: Redis está inacessível
        labels:
          severity: critical
          
      - title: GPU Indisponível
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: nvidia_gpu_power_usage_watts == 0
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: threshold
        noDataState: Alerting
        execErrState: Error
        for: 1m
        annotations:
          summary: GPU está indisponível ou com problema
        labels:
          severity: critical 